### ISSUE TITLE
solid body files?

### ISSUE THREAD

**Issue by hanhanhan-kim** [pohjolaworks/Umo#1]
Hello! This case is very beautiful. I was wondering if it might be possible to release the solid body files (e.g. `.step`) for easier modification of the case? I would be interested in modifying this case for similar boards, like the Planck and the Preonic. Thanks very much!

**Comment by ErkHal** [comment]
@hanhanhan-kim omg, no idea why I haven't received a notification for this message, just noticed this by accident when checking the repo ! Are you still interested in these files ? I can push them into the repo :) Again, so sorry for missing your message !

**Comment by ErkHal** [comment]
@hanhanhan-kim I've now uploaded the STEP files, they are located in the `STEPs` folder. Sorry for this taking so long to notice this issue !
